api_app/urls.py
from rest_framework import routers

from .views import UserViewSet, TaskViewSet


router = routers.SimpleRouter()
router.register(r'users', UserViewSet)
router.register(r'tasks', TaskViewSet)

urlpatterns = router.urls

task_manager/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('task_app.urls')),
    path('', include(('user_app.urls', 'user_app'), namespace='user_app')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('api_app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_app/urls.py
from django.urls import path

from .views import TaskManagerLoginView, RegisterPageView
from django.contrib.auth.views import LogoutView


urlpatterns = [
    path('login/', TaskManagerLoginView.as_view(), name='login'),
    path('register/', RegisterPageView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(next_page='tasks'), name='logout'),
]

user_app/models.py
from django.db import models

# Create your models here.

user_app/forms.py
from django import forms

user_app/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import FormView

from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login 

# Create your views here.
class TaskManagerLoginView(LoginView):
    fields = '__all__'
    template_name = 'user_app/user_login.html'
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy('tasks')

class RegisterPageView(FormView):
    template_name = 'user_app/user_register.html'
    form_class = UserCreationForm
    redirect_authenticated_user = True
    success_url = reverse_lazy('tasks')

    def form_valid(self, form):
        user = form.save()
        if user is not None:
            login(self.request, user)
        return super(RegisterPageView, self).form_valid(form)

    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('tasks')
        return super(RegisterPageView, self).get(*args, **kwargs)

user_app/templates/user_app/user_login.html
{% extends 'index.html'%}
{% block content%}


<h1 style="padding: 10px 0 0 30px">Login</h1>

<form class="task-wrapper" method="post">
    {% csrf_token %}
    <p style="padding-left: 35px;"><i>Имя пользователя:    </i>{{ form.username }}
    <br><i>Пароль:                        </i>{{ form.password }}</p>
    <input class="button" style="position: absolute; bottom: 69%; left: 63%;" type="submit" value="Login">
</form>

<p style="padding-bottom: 10px; padding-left: 35px">Do not have an account? <a href="{% url 'user_app:register' %}">Register</a></p>

{% endblock content%}

user_app/templates/user_app/user_register.html
{% extends 'index.html'%}
{% block content%}

<h1>Register</h1>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Register">
</form>

<p>Already have an account? <a href="{% url 'user_app:login' %}">Login</a></p>

{% endblock content%}